[package]
name = "x64asm-sys"
version = "0.1.0"
edition = "2021"

[dependencies]
autocxx = "0.26.0"
cxx = "1.0"

[build-dependencies]
bindgen = "0.68"
cc = "1.0.81"
autocxx-build = "0.26.0"
miette = { version = "5", features = ["fancy"] } # optional but gives nicer error messages!